### ISSUE TITLE
pre-built gui controls allows one player to send key control to another player

### ISSUE THREAD

**Issue by fred-wang** [RSamaium/RPG-JS#83] opened 2021-05-27 05:21 UTC
1. Follow the instruction at

    npx degit rpgjs/template my-rpg-game
    cd my-rpg-game
    npm install
    npm run dev

   and use of the fix proposed in #82 so that the pre-built gui controls is displayed by default.

2. Make to players join at http://localhost:3001 or http://192...:3001 (they can be on two separate devices e.g. desktop and mobile, but I'm also able to reproduce this two browser tabs).
3. Move one player next to the old man (EV-1), so that you don't face it.
3. Keep the the second player away from the old man and press the "A" action, perhaps several times, until the man faces the other player.
4. Check first player again, the old man is speaking to them.

This can be tricky to reproduce, but it actually happens quite frequently, making MMORPG  mode with one mobile player not possible. I noticed it first with the Escape button when opening the menu on the mobile, it opens the menu on the desktop.

I can't reproduce on the public demo, maybe players have to belong to the same local network. Or it has to do with the fix from #82.

**Comment by RSamaium** [comment] 2021-06-03 14:19
In reality, there are no problems. 

On port 3001, there is the BrowserSync module that acts. This module synchronizes events between browsers. So, if you press button A, all the others on the same network react.

This is not a problem of the MMORPG itself and it doesn't happen in production.

By the way, if you test on port 3000 (without BrowserSync), the problem is not present

I have to think if I keep BrowserSync, which is very useful for development

**Comment by fred-wang** [comment] 2021-06-03 14:30
I see. Indeed issue does not show up on port 3000. Thanks!

**Comment by RSamaium** [comment] 2021-06-11 12:54
BrowserSync has been removed for the MMORPG

Fixed on the update (alpha.10)

**Closed as completed by RSamaium** 2021-06-11 12:54 UTC
